### ISSUE TITLE
How to work with this plugin?

### ISSUE THREAD

**Issue by Jorjini** [natqe/scss-generator#2]
Hi, can you write full description how to configure, or how to just use this extension?

where i can find this scss boilerplate and ect.

thank you, idea of this plugin is a brilliant! please just fix this little issue :)

**Comment by natqe** [comment]
For working with this plugin, all you ever need to do is to start writing your css selector, and you get autocompletions based on your html markup. you don't need to do anything for getting this plugin to work, except of creating your scss file in same directory of your html file, or to call your scss file with same name as your html file.

The extension also provide special snippet called "scss boilerplate for current file" that you can get in your scss file.

**Comment by Jorjini** [comment]
> The extension also provide special snippet called "scss boilerplate for current file" that you can get in your scss file.

where i can find this snipped?

**Comment by natqe** [comment]
for getting these snippet you need to start write those words - "scss boilerplate for current file"
